/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:35b1b555-2ef6-49b9-8e79-bcaf850d17e8",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_63M1Ynsui",
    "aws_user_pools_web_client_id": "7r8i0ucr6k8vlq35fu5stnmg5a",
};


export default awsmobile;
